

RESOLUTION = (3072, 1920)
WIDTH = RESOLUTION[0]
HEIGHT = RESOLUTION[1]
MIN_RESOLUTION = (600, 400)
MIN_WIDTH = MIN_RESOLUTION[0]
MIN_HEIGHT = MIN_RESOLUTION[1]

# Model Parameters
MODEL_WIDTH = 20
MODEL_HEIGHT = 20
MODEL_NODE_COUNT = 50

# Simulated Annealing Parameters
INITIAL_TEMPERATURE = 500
SCHEDULE_CONST = .99999

# Render Parameters
GRAPH_PADDING = 100
GRAPH_LINE_WIDTH = 4
GRAPH_NOTCH_SPACING = 2
GRAPH_NOTCH_LENGTH = 20
GRAPH_COLOUR = (0, 0, 0)

NODE_RADIUS = 5
NODE_COLOUR = (255, 0, 0)

EDGE_WIDTH = 2
EDGE_COLOUR = (0, 0, 0)